openapi: 3.0.0
info:
  description: "RPC API to execute Lifecycle Transitions and Operations"
  version: "1.0.0"
  title: Lifecycle
servers:
  - url: /api/lifecycle
tags:
  - name: lifecycle
    description: Lifecycle Transitions and Operations
paths:
  /execute:
    post:
      tags:
        - lifecycle
      summary: Execute Lifecycle Transition/Operation
      description: >-
        Execute Lifecycle Transition/Operation. If accepted, a response should be returned immediately with a requestId, to refer to the execution process.
        The completion of the request (regardless of whether it was successful or not) should be returned via Kafka (with a message of type ExecutionAsyncResponse from the schema)
      operationId: .execute
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExecutionRequest"
            examples:
              example:
                $ref: "#/components/examples/ExampleExecutionRequest"
      responses:
        "202":
          description: Request accepted (async examples shown for information but they will never be returned via this API, they are returned on Kafka instead)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExecutionAcceptedResponse"
              examples:
                response:
                  $ref: "#/components/examples/ExampleExecutionAcceptedResponse"
                async-response:
                  $ref: "#/components/examples/ExampleExecutionAsyncResponse"
                failed-async-reponse:
                  $ref: "#/components/examples/ExampleFailedExecutionAsyncResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                example: 
                  $ref: "#/components/examples/ExampleExecuteErrorResponse"
components:
  schemas:
    ErrorResponse:
      type: object
      properties: 
        localizedMessage: 
          type: string
          description: Summary of the error that occurred 
        status:
          type: integer
          description: HTTP status code
    ExecutionRequest:
      type: object
      properties:
        lifecycleName:
          type: string
          description: Name of the transition or operation to execute
        lifecycleScripts:
          type: string
          format: byte
          description: Base64 encoded zipped contents of the Lifecycle directory for the Resource
        systemProperties:
          $ref: "#/components/schemas/Properties"
          description: properties generated by LM for this Resource (instance_id, instance_name)
        properties:
          $ref: "#/components/schemas/Properties"
          description: property values of the Resource (includes any output values returned by the create infrastructure request, if this Resource has infrastructure, even if the output property is not on the Resource descriptor)
        deploymentLocation:
          $ref: "#/components/schemas/DeploymentLocation"
      required:
        - lifecycleName
        - systemProperties
        - deploymentLocation
        - lifecycleScripts
    Properties:
      type: object
      additionalProperties:
        type: object
        properties:
          value:
            type: string
          type:
            type: string
    ExecutionAcceptedResponse:
      type: object
      properties:
        requestId:
          type: string
          description: ID associated to the request handling the execution
      required:
        - requestId
    ExecutionAsyncResponse:
      type: object
      properties:
        requestId:
          type: string
          description: ID of the request
        status:
          $ref: "#/components/schemas/LifecycleTaskStatus"
        failureDetails:
          $ref: "#/components/schemas/FailureDetails"
        outputs:
          type: object
          description: Output values returned on completion
    DeploymentLocation:
      type: object
      description: A Deployment Location to manage Resources in
      properties:
        name:
          type: string
          description: Name of the deployment location
        type:
          type: string
          description: Type of location (Infrastructure Type)
        properties:
          type: object
          description: Properties used to provide access to the location
      required:
        - name
    LifecycleTaskStatus:
      type: string
      description: Status of the Lifecycle execution
      enum:
        - IN_PROGRESS
        - COMPLETE
        - FAILED
    FailureDetails:
      type: object
      description: Details of the failure (if the status is FAILED)
      properties:
        failureCode:
          $ref: "#/components/schemas/FailureCode"
        description:
          type: string
          description: Summary of the failure
    FailureCode:
      type: string
      description: Code assigned to the type of error
      enum:
        - RESOURCE_ALREADY_EXISTS
        - RESOURCE_NOT_FOUND
        - INFRASTRUCTURE_ERROR
        - INSUFFICIENT_CAPACITY
        - INTERNAL_ERROR
  examples:
    ExampleExecuteErrorResponse:
      value:
        localizedMessage: No lifecycle script with name "Start"
        status: 400
    ExampleExecutionRequest:
      value:
        lifecycleName: Start
        lifecycleScripts: 
        systemProperties:
          resourceId: be3870d2-891c-487e-9736-ca19e4741cf4
          requestId: a44ac9db-1625-4a9b-87c5-6e77bd88c08a
          resourceManagerId: brent
          deploymentLocation: TestLocation
          resourceType: resource::helloworld::1.0
        properties:
          propA: valueA
          propB: valueB
        deploymentLocation:
          name: Example
          properties: {}
          type: Openstack
    ExampleExecutionAcceptedResponse:
      value:
        requestId: 2b84e4da-663c-41a5-a637-8695fcec314f
    ExampleExecutionAsyncResponse:
      value:
        requestId: 2b84e4da-663c-41a5-a637-8695fcec314f
        status: COMPLETE
        outputs:
          propA: valueA
          propB: valueB
    ExampleFailedExecutionAsyncResponse:
      value:
        requestId: 2b84e4da-663c-41a5-a637-8695fcec314f
        status: FAILED
        failureDetails:
          failureCode: INTERNAL_ERROR
          description: There was an error